language: rust
env: TARGET_ARCH=x86_64 TARGET_VENDOR=-unknown TARGET_OS=linux-gnu FEATURES=bus
rust:
  - stable
  - beta
  - nightly

script:
  - ci/script.sh

after_success:
  - ci/travis-doc-upload.sh
